### ISSUE TITLE
Playtest 1

### ISSUE THREAD

**Issue by doctornewton** [Game-Jam-24/Dungeons-of-Apathy#15]
Level 1 Playtest

items to focus on
 - character animation  correct
 - main hub enter / exit 
 - level 1 interactions working
     - terrain collisions
     - enemy hit box / health / death
     - level completion - return to main hub

**Comment by SpoonishBard** [comment]
Iteration 1 plans changed as follows:

- Character Aimation
- Apathy Spread
- Static Dungeon with tutorial.
